### ISSUE TITLE
A bug for Testing 

### ISSUE THREAD

**Issue by lianshi00** [credix-finance/spl-token-faucet#10]
How to say , during my test  ALL the operation of the function are smooth I feel really good .
But during the test page  even I choose the testnet  in the page it always connects the devnet.
I am not sure if it is my opereation are not right.

This is my address  53HfQT7hn8ScNeuCiTd8C2RrM6wFPis1bUgZiSU1YTwk
You can see in my testnet the USDC is 2000
but in testpage I check the balance the USDC is 0, it shows the devnet USDC.

**Comment by MaximPiessen** [comment]
It works perfectly fine on my side :)
